/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:002f108c-7655-4d0a-b7ad-725d72ab4e1c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ZXOTo5tie",
    "aws_user_pools_web_client_id": "3vv20a1a3ar3o4ni1u2mbo6h1g",
    "oauth": {}
};


export default awsmobile;
